-- Sequences
CREATE SEQUENCE carro_generator START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cliente_generator START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE funcionario_generator START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE item_produto_generator START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ordem_servico_generator START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pagamento_generator START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE produto_generator START WITH 1 INCREMENT BY 1;

-- Tabelas
CREATE TABLE tb_cliente (id NUMBER(19,0) NOT NULL, cpf VARCHAR2(50) NOT NULL UNIQUE, telefone VARCHAR2(50) NOT NULL, email VARCHAR2(255) NOT NULL UNIQUE, endereco VARCHAR2(255) NOT NULL, nome VARCHAR2(255) NOT NULL, role VARCHAR2(255) CHECK (role IN ('ROLE_CLIENTE','ROLE_FUNCIONARIO','ROLE_ADMIN')), senha VARCHAR2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE tb_funcionario (salario NUMBER(38,2) NOT NULL, id NUMBER(19,0) NOT NULL, cpf VARCHAR2(50) NOT NULL, email VARCHAR2(255) NOT NULL UNIQUE, login VARCHAR2(255) NOT NULL UNIQUE, nome VARCHAR2(255) NOT NULL, role VARCHAR2(255) CHECK (role IN ('ROLE_CLIENTE','ROLE_FUNCIONARIO','ROLE_ADMIN')), senha VARCHAR2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE tb_produto (preco NUMBER(38,2) NOT NULL, quantidade NUMBER(10,0) NOT NULL, id NUMBER(19,0) NOT NULL, nome VARCHAR2(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE tb_ordemservico (valor NUMBER(38,2) NOT NULL, cliente_id NUMBER(19,0) NOT NULL, id NUMBER(19,0) NOT NULL, descricao VARCHAR2(255) NOT NULL, status_ordem_servico VARCHAR2(255) NOT NULL CHECK (status_ordem_servico IN ('ABERTA','CONCLUIDA','CANCELADA','EM_ANDAMENTO')), status_pagamento VARCHAR2(255) NOT NULL CHECK (status_pagamento IN ('PENDENTE','PAGO','CANCELADO')), PRIMARY KEY (id));
CREATE TABLE tb_pagamento (valor NUMBER(38,2) NOT NULL, cliente_id NUMBER(19,0), id NUMBER(19,0) NOT NULL, forma_pagamento VARCHAR2(50) NOT NULL CHECK (forma_pagamento IN ('PIX','CARTAO_CREDITO','CARTAO_DEBITO','DINHEIRO')), PRIMARY KEY (id));
CREATE TABLE tb_veiculo (ano NUMBER(10,0) NOT NULL CHECK ((ano>=1886) AND (ano<=2050)), cliente_id NUMBER(19,0) NOT NULL, id NUMBER(19,0) NOT NULL, placa VARCHAR2(10) NOT NULL UNIQUE, cor VARCHAR2(30) NOT NULL, marca VARCHAR2(100) NOT NULL, modelo VARCHAR2(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE tb_itemproduto (quantidade NUMBER(10,0) NOT NULL, subtotal NUMBER(38,2) NOT NULL, valor_unitario NUMBER(38,2) NOT NULL, id NUMBER(19,0) NOT NULL, ordem_servico_id NUMBER(19,0) NOT NULL, produto_id NUMBER(19,0) NOT NULL, PRIMARY KEY (id));

-- FKs
ALTER TABLE tb_itemproduto ADD CONSTRAINT FK6rstmcwqom2tqxsr4i0ebbnfp FOREIGN KEY (ordem_servico_id) REFERENCES tb_ordemservico;
ALTER TABLE tb_itemproduto ADD CONSTRAINT FKqudgjmvt3sn6s6fkoromrwf79 FOREIGN KEY (produto_id) REFERENCES tb_produto;
ALTER TABLE tb_ordemservico ADD CONSTRAINT FKfnuuca5gipekth26oggyruov6 FOREIGN KEY (cliente_id) REFERENCES tb_cliente;
ALTER TABLE tb_pagamento ADD CONSTRAINT FK2jijy17ebaheag5rvwmdb0td5 FOREIGN KEY (cliente_id) REFERENCES tb_cliente;
ALTER TABLE tb_veiculo ADD CONSTRAINT FKrv2dkbho7roxmjk3w9vya2r2c FOREIGN KEY (cliente_id) REFERENCES tb_cliente;